# Generated by Django 3.2.8 on 2021-10-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HufGame',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(blank=True, max_length=20, null=True)),
                ('game_tag', models.CharField(max_length=9)),
                ('no_of_quiz', models.IntegerField()),
                ('game_description', models.CharField(blank=True, max_length=100, null=True)),
                ('total_no_qn', models.IntegerField()),
            ],
            options={
                'db_table': 'hufgame',
                'managed': False,
            },
        ),
    ]
