# Generated by Django 3.2.7 on 2021-10-15 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HufQuiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('quiz_max_score', models.IntegerField()),
                ('quiz_description', models.CharField(blank=True, max_length=50, null=True)),
                ('no_of_qn', models.IntegerField()),
                ('total_no_qn', models.IntegerField()),
                ('game_id', models.ForeignKey(db_column='game_id2', on_delete=django.db.models.deletion.DO_NOTHING, to='gameapi.hufgame')),
            ],
        ),
    ]
