# Generated by Django 3.2.7 on 2021-10-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HufQuiz',
            fields=[
                ('quizid', models.IntegerField(primary_key=True, serialize=False)),
                ('quiz_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('quiz_max_score', models.IntegerField()),
                ('quiz_description', models.CharField(blank=True, max_length=50, null=True)),
                ('no_of_qn', models.IntegerField()),
            ],
            options={
                'db_table': 'huf_quiz',
                'managed': False,
            },
        ),
    ]
