# Generated by Django 3.2.7 on 2021-10-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HufQuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionid', models.IntegerField()),
                ('option_description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'huf_quiz_option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HufQuizQn',
            fields=[
                ('quiz_qn_id', models.AutoField(primary_key=True, serialize=False)),
                ('correct_ans', models.IntegerField()),
                ('question_name', models.CharField(max_length=30)),
                ('score_per_qn', models.IntegerField()),
            ],
            options={
                'db_table': 'huf_quiz_qn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HufQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_earned', models.IntegerField()),
                ('duration_taken', models.IntegerField()),
            ],
            options={
                'db_table': 'huf_quiz_result',
                'managed': False,
            },
        ),
    ]
