# Generated by Django 3.2.7 on 2021-10-15 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0001_initial'),
        ('quizapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hufquiz',
            name='game_id',
            field=models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.DO_NOTHING, to='gameapi.hufgame'),
        ),
    ]
