# Generated by Django 3.2.7 on 2021-10-15 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0002_alter_hufquiz_game_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hufquiz',
            name='total_no_qn',
        ),
    ]
