# Generated by Django 3.2.7 on 2021-10-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0002_hufquizoption_hufquizqn_hufquizresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='HufUserAns',
            fields=[
                ('quiz_qn_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_ans', models.IntegerField()),
            ],
            options={
                'db_table': 'huf_user_ans',
                'managed': False,
            },
        ),
    ]
