# Generated by Django 3.2.7 on 2021-10-15 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameapi', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quizapi', '0003_remove_hufquiz_total_no_qn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hufquiz',
            name='game_id',
            field=models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='gameapi.hufgame'),
        ),
        migrations.CreateModel(
            name='HufQuizQn',
            fields=[
                ('quiz_qn_id', models.AutoField(primary_key=True, serialize=False)),
                ('correct_ans', models.IntegerField()),
                ('question_name', models.CharField(max_length=30)),
                ('score_per_qn', models.IntegerField()),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizapi.hufquiz')),
            ],
        ),
        migrations.CreateModel(
            name='HufUserAns',
            fields=[
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='auth.user')),
                ('user_ans', models.IntegerField()),
                ('quiz_qn_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizapi.hufquizqn')),
            ],
            options={
                'unique_together': {('username', 'quiz_qn_id')},
            },
        ),
        migrations.CreateModel(
            name='HufQuizResult',
            fields=[
                ('quiz_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='quizapi.hufquiz')),
                ('score_earned', models.IntegerField()),
                ('duration_taken', models.IntegerField()),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('quiz_id', 'username')},
            },
        ),
        migrations.CreateModel(
            name='HufQuizOption',
            fields=[
                ('quiz_qn_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='quizapi.hufquizqn')),
                ('option_id', models.IntegerField()),
                ('option_description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'unique_together': {('quiz_qn_id', 'option_id')},
            },
        ),
    ]
